### ISSUE TITLE
problems building on tribblix

### ISSUE THREAD

**Issue by thiccelf83** [slicer69/doas#102]
I am having some problems building this on Tribblix, an Illumos based OS.

So far, I have tried the following as per the instructions:

PREFIX=/opt/local gmake
then as root
PREFIX=/opt/local gmake install

and the error I have attached. I also tried

 YACC="bison -y" PREFIX=/opt/local gmake

I have also tried all of this without re-defining prefix, because tribblox does not have a /opt/local, or at least not one with anything in it.

Now, if you'll forgive me for being an idiot, i also tried linking gcc to cc as per the advice of a redditor, that too failed.

and if it matters at all, it appears i do have bison and yacc installed (in usr//ccs/)

Thanks for reading and thanks for your contribution to open source

**Comment by thiccelf83** [comment]
Not sure if my file was attached. Will re-attach it just incase.

[log.txt](https://github.com/slicer69/doas/files/8920186/log.txt)
.

**Comment by thiccelf83** [comment]
thanks
that worked this time, i guess the reason it didnt work before is because i had to both do that in the gmake command and edit it in the make file, anyways. it builds now, sorry for wasting your time. only had to change the prefix to /usr/bin (which triblix uses) after that, thanks again.

**Comment by slicer69** [comment]
You're welcome. Glad it's working.
