### ISSUE TITLE
doas: Operation not permitted

### ISSUE THREAD

**Issue by Tanishq-Banyal** [slicer69/doas#103]
I get this error when trying to launch bash as a different user. Here's a transcript:

```bash
root@land ~ $ cat /etc/passwd
root:x:0:0::/home:/bin/bash
golu:x:1000:1000::/home:/bin/bash

root@land ~ $ cat /etc/doas.conf
permit persist golu

root@land ~ $ ls -ln /usr/bin/doas
-rwsr-xr-x 1 0 0 39008 Jan 26  2022 /usr/bin/doas

root@land ~ $ doas -u golu bash
doas: Operation not permitted
```

**Comment by slicer69** [comment]
Thanks for the detailed report.

I see two potential problems with the above situation.

First, the doas command shown in the last step is initiated by the root user, not by golu. The root user doesn't have any entries in your doas.conf file, so no actions by root are allowed. 

I suspect what you mean to do is either run "doas -u root bash" as the golu user to open bash as root OR have an entry in your doas.conf file which says "permit root as golu" which would allow the root user to perform commands as golu.

The second possible problem is doas, by default, uses the configuration file /usr/local/bin/doas.conf. Your configuration is located at /etc/doas.conf. This means either you've changed the default location or you are actually running OpenDoas, not doas. These are different programs with similar goals, but different file paths and some different features.
