### ISSUE TITLE
doas: invalid option -- ' '

### ISSUE THREAD

**Issue by mko-io** [slicer69/doas#11]
Hi, 
firstly, thank for porting doas, it's a usefull and simple tool.
I successfully installed on my Ubuntu 16.04 machine, most of the command works fine, but the one with "-arg" switch throw me an error:

```
doas chsh "-s sh"
doas: invalid option -- ' '
usage: doas [-ns] [-a style] [-C config] [-u user] command [args]
```

so things like `doas shutdown -p now` doesn't work, however `doas shutdown now` works fine
I think the problem is due to the argument parsing. It would be great someone can fix it, I'm not good at c though.

**Comment by slicer69** [comment]
On Linux you need to pass doas the "--" flag before running commands with "-" arguments. This is covered in the doas manual page. It has to do with the way GNU C parses the command line arguments. So try using

    doas -- shutdown -p now

**Comment by mko-io** [comment]
thank you for the answer. I should read man page more carefully
