### ISSUE TITLE
doas(1) Arguments like in sudo(8)

### ISSUE THREAD

**Issue by vermaden** [slicer69/doas#117]
Hi,

I have a following case.

I need to allow members of `operator` group to just install packages but not to remove or upgrade them.

That is possible with this rule in `sudo(8)`:
```
  %network ALL = NOPASSWD: /usr/sbin/pkg install *
```

Its not possible with `doas(1)` as only these rules are valid in `doas(1)`:
```
  permit :operator as root cmd pkg args install
  permit :operator as root cmd pkg
```

The first one would only allow `operator` member to execute `pkg install` (without any additional arguments) - which pointless of course.

The second would allow `operator` member to execute `pkg install ANYTHING` but also `pkg delete ANYTHING` or generally `pkg ANYTHING` etc.

There is currently not possible to specify such rule as in `sudo(8)` because of 'syntax wrong' error.

Could you implement that?

I really like `doas(1)` minimalism ans security and would DEFINITELY NOT want to get back to `sudo(8)` for several things.

Thanks,
vermaden

**Comment by vermaden** [comment]
For the record ... **Tim Chase** (https://twitter.com/gumnos) suggested using a workaround with 'wrapper' script.

```
# cd /usr/local/bin
# cat << EOF > pkg_install.sh
pkg install "$@"
EOF
# chmod +x pkg_install.sh
```

... and then grant `doas(1)` access to this script.

Hope that helps.

**Comment by slicer69** [comment]
The short answer is no, we won't be implementing new features unavailable upstream. As vermaden suggested, the appropriate approach would be to write a script to handle flexible situations and grant the operator group access to the script.

**Comment by vermaden** [comment]
Understandable.

Can you provide me a contact for 'upstream'?

Thanks.

**Comment by slicer69** [comment]
The upstream version of doas is provided by the OpenBSD project.
