### ISSUE TITLE
doas: syntax error at line 1

### ISSUE THREAD

**Issue by reelsense** [slicer69/doas#12]
>$ doas date
doas: syntax error at line 1

>cat /usr/local/etc/doas.conf
`permit keepenv { PKG_PATH ENV PS1 SSH_AUTH_SOCK } :wheel`

`doas` on FreeBSD 11.0-RELEASE-p10

This worked for the last year or so. What changed?

**Comment by slicer69** [comment]
In this case I think keepenv should be replaced with setenv in the config line listed. As for what changed, we resynced with the upstream OpenBSD code.

**Comment by reelsense** [comment]
Thanks for the help!
