### ISSUE TITLE
doas should check transitive writability of parent directories of config file

### ISSUE THREAD

**Issue by mrdomino** [slicer69/doas#122]
There is a check in `parseconfig` for whether `doas.conf` is writable by group or other, or is not owned by root. However, there is no check for its containing directories. Without this, it is relatively easy to manipulate the contents of `doas.conf`, e.g. by hard-linking a root-owned `doas.conf.example` (or worse, `doas.conf.insecure`) to it.

If desired, I am happy to try and submit a PR implementing this check.

I don't know about upstreamability; I'm happy to try, but it seems like much less of an issue if the configuration file is always located at `/etc/doas.conf`. The security of `/etc` can probably be considered a concern beyond the scope of `doas`.

**Comment by slicer69** [comment]
It should not be possible for a non-root user to create/link a file in a directory which is owned by root and does not grant write access to other users.

It is possible for a non-root user to erase a config directory owned by root, if they control the parent directory, and replace it with their own directory structure and configuration file. However, this should never happen in an half-normal environment as it makes no sense for root to create a config directory for system tools under a user's home. /etc and /usr/local/etc should never be owned by non-root users.

This is outside the scope of doas.

**Comment by mrdomino** [comment]
`/usr/local` was commonly owned by non root with homebrew on OS X until recently.

You could make the same argument with regard to the file permissions; why have the check at all?

**Comment by mrdomino** [comment]
It's just a sanity check, in case someone has created a custom installation that they didn't realize was broken. I bet if the check were turned on it would break some people still on an old version of OS X with `/usr/local` owned by their user account.
