### ISSUE TITLE
Allow multiple password attempts.

### ISSUE THREAD

**Issue by lefuglyduck** [slicer69/doas#123]
The reason I favor multiple password attempts is that I have some shell scripts which contain multiple commands individually requiring elevated privileges. In some cases, the commands take so long to execute (such as compiling) that I need to reenter the password in the middle of the program. If I reenter the password incorrectly, it will exit the script somewhere in the middle. I mostly use the password attempts in cases where I cannot have the elevated privileges fail and would like to protect against my clumsy typing.

**Comment by slicer69** [comment]
This is outside our scope and won't be implemented.

Having doas run inside scripts is really not recommended. For this sort of thing the script should either be run with doas or the specific commands doas is used to run should be added to the doas.conf file to avoid password prompts.
