### ISSUE TITLE
Are 6.3p11 and 6.3p12 stable releases?

### ISSUE THREAD

**Issue by ryandesign** [slicer69/doas#132]
Are 6.3p11 and 6.3p12 stable releases? The tags were created in May but there is no corresponding GitHub release for these tags. The latest release shown on the project's main page is 6.3p10.

**Comment by ryandesign** [comment]
Ok great. Could you create the missing releases, please, so that that's clear to everyone viewing the main page?

**Comment by slicer69** [comment]
Sure, I'll make a post about the change.
