### ISSUE TITLE
Add `doas` to `brew` package manager

### ISSUE THREAD

**Issue by Neved4** [slicer69/doas#139]
More of an inquiry, really. I'm trying to get `doas` onto [homebrew-core/pull/195436](https://github.com/Homebrew/homebrew-core/pull/195436), but it requires installing it as setuid root:

https://github.com/slicer69/doas/blob/64ccf5521433502379cab26596ac4eb60a8cb523/doas.c#L381-L382

At the same time, Homebrew discourages it, that functionality has been declined several times.

Not sure if I'm missing something here.

Is there any way around this or that you'd be open to that makes sense for `doas`?

**Comment by slicer69** [comment]
The doas program requires setuid to function, as do similar programs like sudo. There isn't any way around it.
