### ISSUE TITLE
persist option does not work on FreeBSD

### ISSUE THREAD

**Issue by wezm** [slicer69/doas#15]
Specifying `persist` in `doas.conf` still results in a password prompt, even immediately after entering it for a preceding command. I believe this is due to FreeBSD not supporting the [TIOCCHKVERAUTH ioctl](https://github.com/slicer69/doas/blob/fe6d3a342b8e42512ce45b626684361a8814c4eb/doas.c#L258)  that drives this feature.

I figure this is not something this project can easily fix but having a open issue might help anyone else that runs into it. It would be nice if `persist` was rejected where not supported or a warning issued instead.

**Comment by slicer69** [comment]
I'm open to the idea of printing an error when a keyword cannot be used, as is the case with persist. Though if more features are added upstream in the future, this could become a growing list. I'd rather not have a different warning printed for each difference across platforms.

At the moment the manual page already contains a warning letting users know the persist keyword only functions on OpenBSD. I'm hoping most users will learn about the doas.conf syntax from the manual page and would therefore learn about the missing featuring on Linux and FreeBSD right from the documentation.

**Comment by wezm** [comment]
> At the moment the manual page already contains a warning letting users know the persist keyword only functions on OpenBSD.

Oh I didn't know that. I didn't look at the man page as I was already familiar with the syntax from using it on OpenBSD. It's probably reasonable for it to just be there.

**Comment by fengsi** [comment]
So won't fix?  Maybe we should keep this ticket open...

**Comment by slicer69** [comment]
Yes, I'd consider this a won't fix (or perhaps more accurately) won't add.

**Comment by Godnyx** [comment]
Just have to say that it works on Linux

**Comment by wezm** [comment]
If that's the case then the man page should be updated https://github.com/slicer69/doas/blob/967418e3e7d7fb5ecb1d0a6d6504d712c1962aa8/doas.conf.5#L55

**Comment by slicer69** [comment]
persist does not work on Linux or FreeBSD or any non-OpenBSD platform.

**Comment by Godnyx** [comment]
> persist does not work on Linux or FreeBSD or any non-OpenBSD platform.

Void and Alpine linux use [this](https://github.com/Duncaen/OpenDoas) version and "persist" works. I also thinks that it works on Artix linux but I'm not 100% sure.

**Comment by slicer69** [comment]
OpenDoas is an entirely separate project and not related to this doas project.

**Comment by leath-dub** [comment]
Just for closure, I made a fork of OpenDoas (and pr) that works on FreeBSD with persist: https://github.com/leath-dub/OpenDoas

I have raise a pr for the port: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279598

**Comment by rempas** [comment]
> Just for closure, I made a fork of OpenDoas (and pr) that works on FreeBSD with persist: https://github.com/leath-dub/OpenDoas
> 
> I have raised a pr for the port: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279598

That's awesome! Thank you!
