### ISSUE TITLE
persist_timestamp

### ISSUE THREAD

**Issue by stewie** [slicer69/doas#16]
https://github.com/Duncaen/OpenDoas/commit/1899c37ea48dd1932edd913c510411ee4c9c242f

Please consider incorporating this timeout functionality

**Comment by stewie** [comment]
It adds the ability to configure a timeout duration, a feature which is offered by sudo.

**Comment by slicer69** [comment]
A timeout duration for what, persistence? Because persistence is not featured in this port of doas.
