### ISSUE TITLE
suid bit question

### ISSUE THREAD

**Issue by ng-0** [slicer69/doas#19]
```
chmod 4755 $(DESTDIR)$(PREFIX)/bin/$(BIN)
```

shouldn't this be 4750? Or is this intended to be writable by everyone?

**Comment by ng-0** [comment]
It works as is, but I'm trying to address a warning pkgsrc gives
(warning: /usr/work/wip/doas/work/.destdir/usr/pkg/bin/doas: set-uid or set-gid files should not be writable by anyone)

**Comment by slicer69** [comment]
I think there is a misunderstanding here. Permissions 4755 mean the file is only writeable by the owner (typically the root user). The file isn't writeable by anyone else. Permissions 4755 mean the owner (root) can read, write and execute. The group and other users can read and execute. The group and other users cannot write to the file.

A permission set of 4750 would mean that root can read, write and execute. The group (probably also root) can read and execute. No one else on the system would be able to read, write or execute the file. This would prevent virtually every user on the system from being able to run doas.

**Comment by ng-0** [comment]
Okay, thanks.

Someone else explained the warning to me and it's alright. Closing.
