### ISSUE TITLE
macOS doas id 

### ISSUE THREAD

**Issue by grylem** [slicer69/doas#28]
Hello
for old version had
$ does id .... egid=20(staff)....
the new version does not have this
with same doas.conf
Thanks.

**Comment by slicer69** [comment]
If I understand your report correctly, this is intentional. The latest version of doas does not carry forward groups as group permissions are dropped.

**Comment by grylem** [comment]
maybe, but in my case with new version
$ doas vim file
vim start up without plugin .vimrc etc from $HOME
old version works fine and I found only this difference between versions

**Comment by slicer69** [comment]
Yes, past versions kept many environment variables, such as $HOME. This has been modified in the most recent release to avoid information leaking or file permission issues.

If you still want to have your $HOME variable when using doas, add the term "keepenv" to your doas.conf file. For example "permit keepenv grylem as root".

**Comment by grylem** [comment]
I have this string in doas.conf but alas.

**Comment by slicer69** [comment]
Could you please post your doas.conf file along with the output of "doas set"?

**Comment by grylem** [comment]
of course
"doas set" command not found
[conf.zip](https://github.com/slicer69/doas/files/4001647/conf.zip)

**Comment by slicer69** [comment]
I believe I found the problem. It looks like the HOME variable is always getting reset to the target user's home, even when keepenv is specified in the doas.conf file. Basically this means you're always getting the root user's .vimrc file instead of your own, even when keepenv is enabled. I'll look into this and try to fix it for the next release.

**Comment by slicer69** [comment]
I believe this is now fixed. I've texted it on Linux and FreeBSD (don't have a macOS machine to confirm, but it should work). You can try the latest 6.2p4 release to test the fix. I'm closing this report, please open a new issue if the problem persists. 

Thanks for your help tracking down the issue.
