### ISSUE TITLE
Request: provide sample doas.conf

### ISSUE THREAD

**Issue by Ottaviocr** [slicer69/doas#29]
It would be handy to provide a sample doas.conf in sources. This would save the user time figuring it out from the man pages or coming back to the Github page for this project.

An example could be the one in OpenBSD base:
https://cvsweb.openbsd.org/src/etc/examples/doas.conf?rev=1.1&content-type=text/x-cvsweb-markup

Thanks.

**Comment by slicer69** [comment]
I think this makes a lot of sense. I'll add a sample configuration file in the next source release.

**Comment by Ottaviocr** [comment]
Thanks.
