### ISSUE TITLE
macOS and PATH

### ISSUE THREAD

**Issue by grylem** [slicer69/doas#30]
Hi
after deep testing, I found a couple more problems with PATH and env.
pkg-config in /opt/local/bin
doas make install
pkg-conf not found etc.
sudo make install - everything is good

path for ocaml bin/libs is /opt/local
doas make install
trying to install to /usr/local with errors instead /opt/local
sudo make install - everything is good

With old version of your doas no problem at all
Regards.

**Comment by slicer69** [comment]
Could you please post your doas.conf file? This sounds like a case of the "keepenv" keyword not being used in doas.conf, but I'll be happy to look into it. In the meantime you should be able to set the PATH variable for the target user through the setenv keyword in doas.conf.

**Comment by grylem** [comment]
I think this is a continuation of
https://github.com/slicer69/doas/issues/28#issuecomment-568991085

**Comment by slicer69** [comment]
With no updates on either issue in the past year, I'm going to consider this one closed. Please re-open if the problem persists.
