### ISSUE TITLE
[Feature request] optional PAM support

### ISSUE THREAD

**Issue by vaygr** [slicer69/doas#33]
Hello,

`doas` is great. And I was glad to find out a Linux port for it.

However all my systems are PAM-less (and I don't use Slackware, which is PAM-less too).

Do you think it's possible to make PAM support non-mandatory in doas for Linux?

**Comment by slicer69** [comment]
I'm glad you're enjoying doas, and I hope you continue to find it useful.

PAM-less systems (and systems with cannot install PAM) are very rare and I'm not sure there is much benefit to supporting them. Which systems are you running that can't use PAM?

Slackware now includes PAM by default, at least in its -current branch. All future releases will use it.

It's possible to include an authentication method that doesn't use PAM, but it'll add a good deal of extra code and some complexity which is what we're trying to avoid in doas (as opposed to sudo). There would need to be a strong case or a lot of distros not willing to package PAM to make PAM-less authentication appealing.

**Comment by terefang** [comment]
one use case would be small (busybox) systems having only glibc and busybox (and maybe klish) installed

**Comment by slicer69** [comment]
I don't think there are enough systems that lightweight to justify adding complexity to doas. Even Alpine, which is a very minimal distro with glibc and Busybox packages and runs doas.

**Comment by vaygr** [comment]
For those interested in a PAM-free version of this, I found [doas fork](https://github.com/Duncaen/OpenDoas) that's also known as [opendoas](https://archlinux.org/packages/community/x86_64/opendoas/) package (e.g. in ArchLinux).
