### ISSUE TITLE
[duplicate] doas with tee breaks - piping on linux

### ISSUE THREAD

**Issue by hisacro** [slicer69/doas#34]
```
echo "testing" | doas tee file
```
this prompts for a password but after entering shell becomes inactive.. features useful especially inside vim 
`:w !doas tee %` 

on openBSD, the same commands works as intended echoes "testing" to stdout and writes "testing" to file.

**Comment by hisacro** [comment]
https://github.com/slicer69/doas/issues/17#issuecomment-471360026
>On Linux piped data is not being forwarded to the command run by doas, it is intercepted by doas. Will look into that further.

duplicate, someone already reported this.

**Comment by hisacro** [comment]
any updates regarding this issue

**Comment by slicer69** [comment]
I can confirm this issue on Linux, but only on Linux. It doesn't appear to be an issue on other platforms. Will look into it a little more, but this is probably going to be marked/documented as a Linux-specific issue rather than changed.
