### ISSUE TITLE
no password prompt on CentOS 7

### ISSUE THREAD

**Issue by cypa** [slicer69/doas#35]
doas do not asks for password

```
test ~ $ cat /etc/doas.conf 
permit asurkov as root
test ~ $ doas ls
doas: authentication failed
test ~ $
```
Makefile:
...
PREFIX?=/
MANDIR?=/usr/share/man
SYSCONFDIR?=/etc
...

**Comment by slicer69** [comment]
CentOS is probably blocking doas from authenticating. You should be able to work around this by copying the /etc/pam.d/sudo file to /etc/pam.d/doas. I have't tried this on CentOS, but it works on macOS.

**Comment by cypa** [comment]
indeed, thank you very much
It works now

**Comment by slicer69** [comment]
I have added this troubleshooting step to the README file in case anyone else runs into the same problem.

**Comment by cypa** [comment]
thanks again22:41, 7 июня 2020 г., Jesse Smith <notifications@github.com>:
I have added this troubleshooting step to the README file in case anyone else runs into the same problem.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
