### ISSUE TITLE
[INFO] Why nopersist doesn't work on linux, and why is not gonna be implemented

### ISSUE THREAD

**Issue by toniz4** [slicer69/doas#37]
Hello, i find this program awesome, it does almost everything i need, but the only thing keeping me from uninstalling sudo and running only doas is nopersist. There is a reason why you will not port that to linux? Will make the program too complex, or unsafe?

Thanks for your time and keep up the great work!

**Comment by slicer69** [comment]
There are a few reasons for not including persist. Porting effort and security/complexity are two. The big one though is wanting to avoid the common alias attack that plagues sudo. 

My philosophy is that if you want to perform a one-off command you can use plain doas, if you need to run multiple commands in a row, then use "doas -s". I don't want to put what I see as a significant security hole in doas just so people can avoid running "doas -s".
