### ISSUE TITLE
Strange behavior compiling on Fedora

### ISSUE THREAD

**Issue by msmafra** [slicer69/doas#38]
Hello!
The last times I tried to compile a new version of _doas_ with a new released version I noticed that I get this strange behavior on my machines: both are with Fedora 32; When I pull the new updates from Github and compile on my main machine by running _make && doas/sudo make install_, /usr/local/bin/doas is not replaced by the new version even if I remove /usr/local/bin/doas before compiling. If I compile on my secondary machine one it works. As I am not familiar with compiling I am not sure if it's some sort of cache happening.
Comparing the files on both machines I get:

**Main machine**
```
ls -alt doas $(command -v doas)
-rwsr-xr-x. 1 root    root    45328 ago  8 16:33 /usr/local/bin/doas
-rwxrwxr-x. 1 marcelo marcelo 45328 ago  8 16:33 doas
```

**My secondary machine**
```
ls -alt doas $(command -v doas)
-rwsr-xr-x. 1 root    root    46528 ago  8 15:42 /usr/local/bin/doas
-rwxr-xr-x. 1 marcelo marcelo 46528 ago  8 15:42 doas

```

Which also made me think if the other necessary files are being replaced/updated.

**Comment by slicer69** [comment]
Why do you think doas is not being installed/overwritten correctly? From the output you posted here, it looks like the newly compiled version  is being installed on both machines. Based on the output show here both the compiled version and the installed version are the same size and have the same creation time, so what makes you think it's not the right file?

**Comment by msmafra** [comment]
> Why do you think doas is not being installed/overwritten correctly? From the output you posted here, it looks like the newly compiled version is being installed on both machines. Based on the output show here both the compiled version and the installed version are the same size and have the same creation time, so what makes you think it's not the right file?

Actually not. I forgot to point out that each ls command is showing the doas from my clone of the repo (~/Projects/doas) and the one installed in /usr/local/bin/. If you observe the main machine one is smaller than the one from my secondary machine.

**Comment by slicer69** [comment]
Yes, I understood what the commands and output were showing. I still do not understand why you think there is a problem. It looks like both copies on the same machine are the same size. Which is what I would expect.

The fact the executable are different sizes on different machines is not necessarily a sign of a problem.

What makes you think the executable you have installed are not the right one?

**Comment by msmafra** [comment]
> Yes, I understood what the commands and output were showing. I still do not understand why you think there is a problem. It looks like both copies on the same machine are the same size. Which is what I would expect.
> 
> The fact the executable are different sizes on different machines is not necessarily a sign of a problem.
> 
> What makes you think the executable you have installed are not the right one?

I noticed that when you released 6.3 with the -S parameter. Worked on the secondary machine but not on the main one. Any other way I can know which version I am on?

I copied from the secondary one to /usr/local/bin/:
```
❯ ls -alt ~/Projects/doas/doas $(command -v doas)
-rwsr-xr-x. 1 root    root    46528 ago  8 16:56 /usr/local/bin/doas
-rwxrwxr-x. 1 marcelo marcelo 45328 ago  8 16:10 /home/marcelo/Projects/doas/doas
```

**Comment by slicer69** [comment]
You can test if you are running the latest version by running the command "doas uname -r". If it works then you have the latest version. If it gives an error about doas not recognizing "-r" then you have an older version than the latest.

You can also check to see if you have "vidoas" installed by running "which vidoas". If not, then something went wrong installing the new version.

My best guess, if there is a problem, is that "make clean" was not run before "make; make install", which could result in the build system keeping the original version if Make was not detecting the newer source files for some reason.

**Comment by msmafra** [comment]
> You can test if you are running the latest version by running the command "doas uname -r". If it works then you have the latest version. If it gives an error about doas not recognizing "-r" then you have an older version than the latest.
> 
> You can also check to see if you have "vidoas" installed by running "which vidoas". If not, then something went wrong installing the new version.
> 
> My best guess, if there is a problem, is that "make clean" was not run before "make; make install", which could result in the build system keeping the original version if Make was not detecting the newer source files for some reason.

Actually I run make clean on some tests. I also checked some btrfs parameters, but it seems fine. vidoas I saw that was copied at the first try, I just did not test with no --, but is working "doas uname -r" despite both having different sizes.
Thanks for your time. Sorry about that. If I discover why. I'll get back to you.

Thanks for the amazing port.

**Comment by slicer69** [comment]
Sounds like you've got the latest version so all is well. Cheers!

**Comment by msmafra** [comment]
Cheers!
