### ISSUE TITLE
The configuration file is not honoring Makefile's PREFIX

### ISSUE THREAD

**Issue by scrouthtv** [slicer69/doas#39]
I changed the second line of the `Makefile` to
```
PREFIX?=/usr
```
However, the configuration file is still read from `/usr/local/`:
```
 ~ cat /etc/doas.conf
permit :wheel
 ~ doas whoami
doas: doas is not enabled, /usr/local/etc/doas.conf: No such file or directory
 ~ 
```
How can I fix this?

**Comment by slicer69** [comment]
The location where doas looks for its configuration file is stored in the SYSCONFDIR variable in the makefile. This variable is, by default, defined as

"$(DESTDIR)$(PREFIX)/etc"

Which means if you change PREFIX and then do a "make clean; make; make install" doas will look for its configuration file in $PREFIX/etc.

You said this is not happening, that you've set PREFIX to be /usr and it is not being respected. I suspect that means your system already defines PREFIX somewhere else as /usr/local. In which case you need to change the line in the makefile from

     PREFIX?=/usr

to

     PREFIX=/usr

The question mark means the variable is only set if it is not defined elsewhere on your system. To override local defaults by those in the Makefile remove the question mark.

**Comment by scrouthtv** [comment]
Thank you for the quick help!
