### ISSUE TITLE
No make uninstall

### ISSUE THREAD

**Issue by scrouthtv** [slicer69/doas#40]
`make uninstall` is missing:
```
 ~ sudo make uninstall
make: *** No rule to make target 'uninstall'.  Stop.
```

Should I manually remove the files installed by `make install`?

**Comment by slicer69** [comment]
You can manually remove doas files if you want. There are only a few /usr/local/bin/doas, /usr/local/bin/vidoas, the manual pages (for doas and doas.conf), and the configuration file. Typically clean-up is handled by the system's package manager.
