### ISSUE TITLE
on ubuntu 18.04 I still need to add my password when I do doas, on 20.04 I dont have to

### ISSUE THREAD

**Issue by matthiasdebernardini** [slicer69/doas#42]
I first tried this on ubuntu  20.04 and it worked just fine, but I had to downgrade to 18.04 for a project and I noticed that I get asked to put my password in everytime I use the program but on 20 I didnt.

I have `permit m as root` in usr/local/etc/doas.conf

vidoas didnt report any problems when I ran it. 

Is it supposed to ask for password everytime? On ubuntu 20 it doesn't and I liked that, I could run `doas apt update` and it just worked

**Comment by slicer69** [comment]
Yes, doas is always supposed to ask you for a password every time, unless you have "nopass" set in the doas.conf file. If it wasn't asking for a password and you did not have "nopass" specified in your doas.conf file, then there is a bug in the Ubuntu 20.04 version.

How are you installing doas on Ubuntu?

**Comment by matthiasdebernardini** [comment]
You know what I forgot that I had set nopass in my ubuntu 20 - this was a huge misunderstanding, I'm sorry I'll be closing. Thank you for the help.
