### ISSUE TITLE
Password feedback?

### ISSUE THREAD

**Issue by SandWoodJones** [slicer69/doas#49]
I've changed from using sudo to doas recently but I've been missing the `passwdfb` option I had set on my `sudoers`. It shows your password in asterisk form just like you would see when inputting a password through your browser.

**Comment by slicer69** [comment]
I really don't like the idea of giving password feedback as it feels very un-UNIXy. I also would rather not introduce options that are not included upstream and I don't think password feedback is included in the OpenBSD version. I'd consider accepting a patch for it if it can be done cleanly across supported platforms, but I won't be implementing this feature myself.

**Comment by slicer69** [comment]
Closing this. If someone has a patch for the request I'll look at it.
