### ISSUE TITLE
strange `sort` behaviour when using doas

### ISSUE THREAD

**Issue by rpolve** [slicer69/doas#52]
5.9.6-arch1-1

opendoas 6.6.1-2
sort (GNU coreutils) 8.32

Hi. I don't understand why `sort` behaves differently when coupled with `doas`. Can you help me make sense of this?

$ cat test

```
BBBBBBBBBB
aaaaaaaaaa
__________
AAAAAAAAAA
0000000000
----------
1111111111
bbbbbbbbbb
```

$ sort test

```
----------
__________
0000000000
1111111111
aaaaaaaaaa
AAAAAAAAAA
bbbbbbbbbb
BBBBBBBBBB
```

$ sudo sort test

```
----------
__________
0000000000
1111111111
aaaaaaaaaa
AAAAAAAAAA
bbbbbbbbbb
BBBBBBBBBB
```

$ doas sort test

```
----------
0000000000
1111111111
AAAAAAAAAA
BBBBBBBBBB
__________
aaaaaaaaaa
bbbbbbbbbb
```

$ doas sort -f test

```
----------
0000000000
1111111111
AAAAAAAAAA
aaaaaaaaaa
BBBBBBBBBB
bbbbbbbbbb
__________
```

**Comment by slicer69** [comment]
This is not the project page for opendoas, this is the page for doas. It's an unrelated project.

However, I suspect what is happening is opendoas is stripping the locale information from your environment for security purposes. The sort manual page has an important warning about this situation: "*** WARNING *** The locale specified by the environment affects sort order.  Set  LC_ALL=C  to get the traditional sort order that uses native byte values."
