### ISSUE TITLE
How to stop using quotation marks?

### ISSUE THREAD

**Issue by Joe23232** [slicer69/doas#56]
In the program `sudo` I don't have to use quotation marks when passing in multiple arguments.
e.g. `sudo pacman -S firefox`.

With `doas`, the last time I saw it in action, you _do_ have to use quotation marks when passing in multiple arguments.
e.g. `doas "pacman -S firefox"`

Is there a way to stop using quotation marks?

**Comment by slicer69** [comment]
You don't need to use quotation marks to pass arguments to doas anymore. The past few versions didn't require this.

Previously you could use "--" in front of commands instead of quotes, but that isn't required anymore either.

**Comment by Joe23232** [comment]
Oh ok my bad I didn't realise that, thanks for letting me know :)

Just out of curiosity, how does `doas` more superior over `sudo`

**Comment by slicer69** [comment]
My pleasure.

This may seem like a strange stance for me as the porter to take, but I'm not sure doas is superior over sudo. What I mean is that doas is intentionally more simplistic. doas is smaller, has limited and clear syntax, and fewer features in an effort to keep the code small and auditable.

sudo has more features, more flexibility, and more convenience.

So I guess it is a matter of preference. Do you like small, clean, clear. Or do you like power, flexibility, and lots of cool features. For most day to day stuff either will do. I think for minimal systems like BSD servers doas makes a lot of sense. For complex, multi user desktop Linux systems then sudo probably makes more sense.

**Comment by Joe23232** [comment]
I see, that makes more sense mate, thanks :)
