### ISSUE TITLE
Nvim cannot find gruvbox scheme color when running with doas

### ISSUE THREAD

**Issue by ltsdw** [slicer69/doas#59]
I have gruvbox installed and working and it's directory is detected by nvim envar as in `VIMINIT=":source $XDG_CONFIG_HOME/nvim/init.vim"` so it matches my user and root when preserving envars, but when running nvim using doas it seems not find gruvbox:

```
Error detected while processing VimEnter Autocommands for "*":
E185: Cannot find color scheme 'gruvbox'
Press ENTER or type command to continue
```
I have these lines at doas.conf:
```
permit keepenv myuser as root
permit myuser as root
```

**Comment by slicer69** [comment]
Why do you have two rules for your user, one which drops environment variables? If you want your user to be able to run a program and use environment variables then you should only have the first rule in your doas.conf file, the one with the "keepenv" keyword. The second rule insures that environment variables will be dropped.

**Comment by ltsdw** [comment]
Oh... I see that, misread the documentation. Closing.
