### ISSUE TITLE
Support for Touch ID on macOS

### ISSUE THREAD

**Issue by axman6** [slicer69/doas#61]
I understand you don't have a Mac to test with, but wanted to see if it was likely there's a simple fix to allow this.

Sudo can be configured in `/etc/pam.d/sudo` to allow authentication using Touch ID by making this change:

```diff
 # sudo: auth account password session
+auth       sufficient     pam_tid.so
 auth       sufficient     pam_smartcard.so
 auth       required       pam_opendirectory.so
 account    required       pam_permit.so
 password   required       pam_deny.so
 session    required       pam_permit.so
```

I tried making the same change in `/etc/pam.d/doas` ands hoped I'd get the same behaviour but sadly a password prompt was still presented in the terminal.

**Comment by slicer69** [comment]
At the moment, no I don't think there is any support for touch ID, on any platform. This might change in the future with some PAM-related tweaks, but right now it's not implemented.

**Comment by axman6** [comment]
Yeah I figured as much, I was having a look at Apple's sudo source code to see if it was obvious but it didn't appear to be.

Thanks for putting in the effort to make doas portable, I'm sure you're going to be getting a lot more interest with the recent sudo news. I was prompted to take a look after watching https://youtube.com/watch?v=eamEZCj-CuQ and seeing just how massive sudo is.

**Comment by YTG1234** [comment]
> I was prompted to take a look after watching youtube.com/watch?v=eamEZCj-CuQ

I actually watched multiple YouTube videos about `doas`, but only today have I decided to finally switch away from `sudo`.

**Comment by slicer69** [comment]
I'll look into it. I'm hoping expanding PAM support to include touch ID will also help streamline the Linux code at the same time. However, it'll probably be a slow move as I don't have any touch/fingerprint devices to trial it against.

Thanks for the encouragement. The past two days have seen a noticeable uptick in doas interest.

**Comment by burnsac5040** [comment]
> I understand you don't have a Mac to test with, but wanted to see if it was likely there's a simple fix to allow this.
> 
> Sudo can be configured in `/etc/pam.d/sudo` to allow authentication using Touch ID by making this change:
> 
> ```diff
>  # sudo: auth account password session
> +auth       sufficient     pam_tid.so
>  auth       sufficient     pam_smartcard.so
>  auth       required       pam_opendirectory.so
>  account    required       pam_permit.so
>  password   required       pam_deny.so
>  session    required       pam_permit.so
> ```
> 
> I tried making the same change in `/etc/pam.d/doas` ands hoped I'd get the same behaviour but sadly a password prompt was still presented in the terminal.

Did you disable System Integrity Protection (SIP) to install doas? Or do anything special that is not in the documentation? I keep getting this error: `doas: not installed setuid`

**Comment by axman6** [comment]
@burnsac5040 See https://github.com/slicer69/doas/issues/60, you need to make the binary setuid yourself (using sudo :( )

**Comment by burnsac5040** [comment]
> @burnsac5040 See #60, you need to make the binary setuid yourself (using sudo :( )

I actually figured it out.  I feel kind of dumb now.  I tried all combinations of (sudo) gmake/make install but never did `sudo make` to begin with, and whenever I did `sudo make`, `sudo make install` I got it to work out.

**Comment by slicer69** [comment]
I'm closing this as it'll probably require someone who has a Mac to patch and test it.
