### ISSUE TITLE
fatal error: security/pam_appl.h: No such file or directory

### ISSUE THREAD

**Issue by harisahmed05** [slicer69/doas#63]
Help please :( 
```
cc -Wall -O2 -DUSE_PAM -DDOAS_CONF=\"/usr/local/etc/doas.conf\"  -D_GNU_SOURCE -include compat/compat.h -Icompat  -c -o doas.o doas.c
doas.c:48:10: fatal error: security/pam_appl.h: No such file or directory
   48 | #include <security/pam_appl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: doas.o] Error 1
```

**Comment by harisahmed05** [comment]
Btw, how to get ``` libpam0g-dev ``` ? in Fedora? I guess, I'm missing some dependencies.

**Comment by slicer69** [comment]
Yes, you are missing the PAM development libraries. Please refer to your distribution's documentation or support forum to find out how to install these.

**Comment by linuxnoob121** [comment]
Hi! I am currently using Debian 10, and I am having the same problem. Can you help me fix it? I have installed this before and it worked perfectly, but I reinstalled my OS and now it won't install.

**Comment by slicer69** [comment]
The command to install all Debian dependencies is listed in the README file.

**Comment by yru-weighed** [comment]
detection impact 
goggle inherit development ipv4 

user@build$ gcc -m32 -fPIC -DPIC -shared -rdynamic -o pam_ignore_32.so pam_ignore.c
  user@build$ gcc -m64 -fPIC - DPA. EUROPEAN  DATA  IGNORE THE TRANSMITAL PH 
INCSSES OF FRAUD WAS BEEN DETECTED MITIGATION -shared -rdynamic -o pam_ignore_64.so pam_ignore.c / run debugging automation software development company 
IPsec 4 iCloud 4  - suspress the termination development inherited Google 
developer slaffy198212023@outlook / executive the device  retina automb  datiechvm lmnj 
Next, we'll install the (PAM/)  introvert of system mitigation \ Blockage derive the exercise 
 cropping module i[ ewide detection impact ] nto the path where it should live. On most Linux systems this is "/lib/security" (or "/lib/security" for 32-bit and "/lib64/security" for 64-bit libraries on 32/64 multilib systems)

  root@test# cp pam_ignore_32.so /lib/security/pam_ignore.so/ detected MITIGATION

  root@test# cp pam_ignore_64.so /lib64/security/pam_ignore.so- volunerability 
  root@test# chown root:root /lib/security/pam_ignore.so /lib64/security/pam_ignore.so
  root@test# chmod 755 /lib/security/pam_ignore.so /lib64/security/pam_ignore.so
