### ISSUE TITLE
prompt times out 

### ISSUE THREAD

**Issue by pnotz17** [slicer69/doas#64]
everything works fine on arch Linux except whemever i try to ` doas pacman -Qqe > pkglist.txt` i cant even finish to type my password and it says` Password: cdoas: authentication failed` can anyoneone help?

**Comment by slicer69** [comment]
That sounds like a problem with the PAM configuration on your distro. doas doesn't have any mechanism for a time out.

**Comment by pnotz17** [comment]
well im looking into it any pointers?i i get a warning when i make the file  from source but i doubt that's the problem
```
compat/execvpe.c: In function ‘execvpe’:
compat/execvpe.c:61:5: warning: ‘nonnull’ argument ‘name’ compared to NULL [-Wnonnull-compare]
   61 |  if ( (! name) || (*name == '\0') ){

```

**Comment by slicer69** [comment]
No, that's a false positive warning from the compiler.
