### ISSUE TITLE
Warnings during PCKGBUILD aur

### ISSUE THREAD

**Issue by simoneruffini** [slicer69/doas#66]
Running '5.10.11-arch1-1'.
Trying to install from AUR 'doas-6.3p2-4' returns this warning messages:
```C++
/usr/include/unistd.h: In function ‘execvpe’:
compat/execvpe.c:110:10: warning: ignoring return value of ‘writev’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  110 |    (void)writev(STDERR_FILENO, iov, 3);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compat/execvpe.c:61:5: warning: ‘nonnull’ argument ‘name’ compared to NULL [-Wnonnull-compare]
   61 |  if ( (! name) || (*name == '\0') ){
      |     ^
```
I don't know if this warning is important, just reporting it.

**Comment by slicer69** [comment]
Thanks for letting me know. I'm not getting the former warning, but I'll look into it. The latter is a compiler false positive. There is a sanity check which the compiler believes doesn't need to be there because the value can't be NULL on Linux, but it might be on other platforms.

**Comment by simoneruffini** [comment]
So compiling through the official way does not return such warnings? Is it just caused by additional parameters in the pckgbuild or there is something different going on?

**Comment by slicer69** [comment]
I also checked the former warning and it's a non-issue. We have no reason to check if the writev() fails because we don't use it for anything other than printing that warning.

**Comment by slicer69** [comment]
Could be a pkgbuild setting, but it's probably just your distro using a new er compiler than mine. Compilers adjust their warnings all the time to add more checks or different flags.
