### ISSUE TITLE
Can't open GUI apps

### ISSUE THREAD

**Issue by uKaigo** [slicer69/doas#67]
I can't open any GUI apps using `doas`.

I tried to run some apps using doas.

When I ran `doas xeyes` I got this error:
```
No protocol specified
Error: Can't open display: :0
```
When I ran `doas drawing` I got:
```
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
```

System Information
==================

- **OS:** Linux Mint 20.1 x86_64
- **Kernel:** 5.4.0-65-generic
- **Shell:** bash 5.0.17

**Comment by slicer69** [comment]
Please read the doas.conf manual page. It explains how to enable GUI applications.

**Comment by uKaigo** [comment]
Oh, missed that.
