### ISSUE TITLE
Missing newline in config causes syntax error

### ISSUE THREAD

**Issue by dosisod** [slicer69/doas#68]
Repo:

```
$ echo -n "permit user" > conf
$ doas -C conf
doas: syntax error at line 1
$ echo "permit user" > conf
$ doas -C conf

<no warning>
```

Took me a while to figure out why it was failing. Would this be something that would be worth fixing/warning the user about?

**Comment by slicer69** [comment]
This is interesting. I confirmed your test works the same here. However, I've also found that creating the doas.conf file in a text editor without specifying the newline on the end still produces a valid file. I'll look into this and either adjust it in the code or make a note in the documentation.

**Comment by slicer69** [comment]
The requirement for a newline at the end of each rule has been documented in the doas.conf manual page.
