### ISSUE TITLE
Doas asking for password every time

### ISSUE THREAD

**Issue by Mythbusters123** [slicer69/doas#69]
I came from sudo, where if you opened a terminal session it would say “ok so u used the password, I’m not going to ask again” but doas makes you enter it every time. I can see the point of doing this, but it’s annoying when trying to install something that asks for root privileges a lot. Thank you!

**Comment by Mythbusters123** [comment]
Also pog 69th issue

**Comment by slicer69** [comment]
This is the intended behaviour.

**Comment by slicer69** [comment]
No.
