### ISSUE TITLE
First input is the only one it takes.

### ISSUE THREAD

**Issue by Gotchfutchian** [slicer69/doas#70]
I know the title is cryptic, but when I run doas before another command, then it asks me for my password, the following would happen,

`Password:
*Input* P`
It then inserts a newline, and exposed the rest of "Password"
It would then fail the authentication check. 
i can happily provide more info if this is not sufficient.

**Comment by Gotchfutchian** [comment]
`gotchfutchian@pop-os:~$ doas mega-get https://mega.nz/file/j3hyVYhb#n0UzyhgRymJCFMg507l_lYdmZuGGTRFjfjFebTaR0UU
Password: 
1m0doas: authentication failed
gotchfutchian@pop-os:~$`
Example

**Comment by slicer69** [comment]
I suspect what is happening is PAM (the software which handles the authentication part) is timing out. Another person reported a similar issue. Chances are you need to have a suitable PAM module on your system.

If you already have sudo installed you can probably do this:

      sudo cp /etc/pam.d/sudo /etc/pam.d/doas

If that doesn't work try creating a new text file called /etc/pam.d/doas and make sure it contains the following lines:

#%PAM-1.0
@include common-auth
@include common-account
@include common-session-noninteractive

**Comment by Gotchfutchian** [comment]
> I suspect what is happening is PAM (the software which handles the authentication part) is timing out. Another person reported a similar issue. Chances are you need to have a suitable PAM module on your system.
> 
> If you already have sudo installed you can probably do this:
> 
> ```
>   sudo cp /etc/pam.d/sudo /etc/pam.d/doas
> ```
> 
> If that doesn't work try creating a new text file called /etc/pam.d/doas and make sure it contains the following lines:
> 
> #%PAM-1.0
> @include common-auth
> @include common-account
> @include common-session-noninteractive

First solution did nothing, even after doing a refresh.
Second already has the file, and already contains all of those lines.

**Comment by Gotchfutchian** [comment]
Ok, I did a full reboot after doing both solutions, seemed to fix it. (on a side note, nopass parameter in the config does not work but that is a minor issue.)
