### ISSUE TITLE
doas.c:380: error: 'DOAS_CONF' undeclared

### ISSUE THREAD

**Issue by prologic** [slicer69/doas#75]
Hi 👋

I'm _trying_ to build this on [prologic/ulinux](https://github.com/prologic/ulinux) and this fails with:

```#!console
# pkg build
=> Saved checksums to build/.checksum
tcc -D_BSD_SOURCE -I/usr/lib/tcc/include -include compat/compat.h -Icompat  -c -o doas.o doas.c
doas.c:380: error: 'DOAS_CONF' undeclared
make: *** [<builtin>: doas.o] Error 1
#
```

Where does `DOAS_CONF` come from? Did I miss something in the build instructions?

My `Pkgfile` / script for building looks like this:

```#!console
# cat Pkgfile
#!/bin/sh
# shellcheck disable=SC2034

# Description: allows a user to run a command as though they were another user
# URL:         https://github.com/slicer69/doas
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=doas
version=6.3p2
release=1
source="https://github.com/slicer69/doas/archive/${version}.tar.gz"

build() {
  cd "$name"-"$version" || exit 1

  make
  make DESTDIR="$PKG" install
}
```

Thanks!

**Comment by prologic** [comment]
Hmm trying to build manually by hand leads to:

```
# make CC=tcc
tcc -Wall -O2 -DUSE_PAM -DDOAS_CONF=\"/usr/local/etc/doas.conf\"  -D_GNU_SOURCE -include compat/compat.h -Icompat  -c -o doas.o doas.c
In file included from doas.c:48:
doas.c:48: error: include file 'security/pam_appl.h' not found
make: *** [<builtin>: doas.o] Error 1
#
```

This _system_ doesn't have any "PAM" -- It's mostly just a busybox userland more or less with a musl libc and tcc C compiler

**Comment by prologic** [comment]
Hmmm building with `-DUSE_BSD_AUTH` isn't going to work either :/

```
# make CC=tcc
tcc -Wall -O2 -DUSE_BSD_AUTH -DDOAS_CONF=\"/usr/local/etc/doas.conf\"  -D_GNU_SOURCE -include compat/compat.h -Icompat  -c -o doas.o doas.c
In file included from doas.c:43:
doas.c:43: error: include file 'bsd_auth.h' not found
make: *** [<builtin>: doas.o] Error 1
#
```

What options do we have here on a very non-traditional system?

**Comment by slicer69** [comment]
To answer your first question, DOAS_CONF is set in the Makefile. It looks like the build process is trying to do things manually rather than run the Makefile or isn't compatible with GNU Make.

As for building doas without doas or BSD Auth, it's not going to work. If the system is so minimal that it doesn't have PAM then it's not going to build/run.

**Comment by prologic** [comment]
> As for building doas without doas or BSD Auth, it's not going to work. If the system is so minimal that it doesn't have PAM then it's not going to build/run.

I take it this pretty much applies to sudo as well? Basically no doas/sudo on busybox-based systems?

**Comment by slicer69** [comment]
I can't speak for the sudo devs, but I know the sudo package on Debian pulls in PAM as a dependency. FreeBSD's sudo port does too, at least with the default build.

**Comment by prologic** [comment]
Yeah no worries. I think it would be difficult to get PAM into this very small system. I'll close this issue, but thanks for responding! 🙇‍♂️
