### ISSUE TITLE
The "permit" command isn't findable.

### ISSUE THREAD

**Issue by SirAxolot** [slicer69/doas#78]
The command I ran: permit [my username] as root
The result: zsh: command not found: permit
I am running this on Manjaro KDE.

**Comment by slicer69** [comment]
permit is not a command, it's a keyword in the doas.conf file. Please read the doas and doas.conf manual pages which come with the program.

**Comment by SirAxolot** [comment]
I sure am the fool here.

**Comment by SirAxolot** [comment]
There is no /usr/local/etc/doas.conf.
When I run "nvim /usr/local/etc/doas.conf", it opens a seemingly blank file.

**Comment by SirAxolot** [comment]
STEPS TO SOLVE:
1) sudo nvim /etc/doas.conf
2) paste "permit <user> as root"
3) :wq
4) Stop wasting slicer69's time.
