### ISSUE TITLE
something odd

### ISSUE THREAD

**Issue by hdatma** [slicer69/doas#79]
```
> doas env | grep ^PATH | tr '\:' '\n' | grep '\/usr\/sbin'
/usr/sbin

> doas whereis pkg_delete
/usr/sbin/pkg_delete

> doas which pkg_delete
/usr/sbin/pkg_delete

> doas pkg_delete
doas: pkg_delete: command not found

> PATH=/bin:/usr/bin:/sbin:/usr/sbin doas pkg_delete
pkg_delete: No packages to delete
```

The same hols for any binary in /sbin and /usr/bin/.

**Comment by slicer69** [comment]
Could you post your doas.conf file along with which operating system you are using? 

What happens if you provide the whole path to pkg_delete? For example:
doas /usr/sbin/pkg_delete

**Comment by hdatma** [comment]
> Could you post your doas.conf file along with which operating system you are using?

```
> uname -a
OpenBSD obsd.local 6.8 GENERIC.MP#5 amd64

> cat /etc/doas.conf
permit nopass keepenv root as root
permit nopass hdatma
```

> What happens if you provide the whole path to pkg_delete? For example:
> doas /usr/sbin/pkg_delete

```
> doas /usr/sbin/pkg_delete  
pkg_delete: No packages to delete
```

**Comment by slicer69** [comment]
You're using OpenBSD's built-in version of doas then, not this software which is a port to other operating systems. Your bug report should be submitted to the OpenBSD team.

**Comment by hdatma** [comment]
Can you forward the issue to them?
