### ISSUE TITLE
Update doas to latest OpenBSD revision

### ISSUE THREAD

**Issue by abishai** [slicer69/doas#8]
I've noticed the latest version supports persist keyword which can simplify doas usage greatly
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/doas/

**Comment by slicer69** [comment]
I'm open to the idea. I'm not sure if this is something I want to tackle personally. But if someone sends me a patch I'll happily test and commit it.

**Comment by slicer69** [comment]
This version of doas is now up to date with changes from OpenBSD's doas.
