### ISSUE TITLE
Differences between this and Duncaen/OpenDoas?

### ISSUE THREAD

**Issue by TheThunderGuyS** [slicer69/doas#80]
I am unable to find any differences between these 2 implementations of doas. This repository has more stars, but less issues and commits. [OpenDoas](https://github.com/Duncaen/OpenDoas) is also the version provided by most binary package repositories.

**Comment by slicer69** [comment]
I'm not familiar with the inner workings of OpenDoas. I do know we get some support requests from people who have confused the two so I know they don't work exactly alike. But I haven't looked into it.
