### ISSUE TITLE
FreeBSD port: `stdout` of sub command got redirected to `stderr`

### ISSUE THREAD

**Issue by abakay** [slicer69/doas#82]
It looks like `stdout` of any `doas` sub command is forcibly redirected to `stderr`. The following command will print nothing to `stdout`/console:

```bash
doas ls 2> /dev/null
```

The `doas` installed via packages on FreeBSD 12.2. Is it expected behaviour? Please advise.

**Comment by slicer69** [comment]
Which shell are you using? On my FreeBSD machine with the default shell (tcsh) that line will give the error "ls 2: no such file or directory". 

If I switch to bash and run "doas ls 2> /dev/null" then I get a directory listing as expected.

**Comment by abakay** [comment]
I tried that command in `sh` and `fish` shells.

It is looks like in `tcsh` is not possible to redirect `stderr` separately from `stdout`. From `man tcsh`:
```
Diagnostic output may be directed through a pipe with the standard output. Simply use the form |& rather than just |.

The shell cannot presently redirect diagnostic output without also redirecting standard output, but (command > output-file) >& error-file is often an acceptable workaround. Either output-file or error-file may be /dev/tty to send out-put to the terminal.
```

**Comment by slicer69** [comment]
I just checked with plain sh (/binsh) on FreeBSD 12.2 and running "doas ls 2> /dev/null" displays a normal directory listing.

**Comment by abakay** [comment]
Ok, I guess I spotted one more difference. I am using `pam_ssh_agent_auth` package on this machine with following PAM configuration:
```
auth            sufficient      /usr/local/lib/pam_ssh_agent_auth.so file=~/.ssh/authorized_keys
auth            required        pam_deny.so
account         include         system
session         required        pam_permit.so
```
Maybe that somehow is contributing to the issue.

**Comment by slicer69** [comment]
Perhaps. I can say that with the default configuration output isn't being redirected so the command you suggested prints output as expected.
