### ISSUE TITLE
doas: syntax error at line 1

### ISSUE THREAD

**Issue by ReduxRoot** [slicer69/doas#84]
After seeing some people recommending using doas instead of sudo, i give it a try, after following some tutorials on YouTube, I have installed but something isn't working, after writing `doas apt install brave` the response was `doas: syntax error at line 1` I tried reinstalling but nothing, am i missing something?

My installation process:
1. Clone the GitHub repo
2. Install the build tools
3. `make`
4. `sudo make install`
5. Create doas.conf and write permit <username> as root
6. And done

Extra info:
OS: Xubuntu 21.04
Kernel: 5.11.0-25-generic
Tools used: sudo, nano, mousepad, vim, xfce4-terminal, thunar etc

Sorry if my English is bad but i tried my best explaining all the process that i did, any help is appreciated!
(Note: doas id doesn't work as well, the only command that works is doas)

**Comment by slicer69** [comment]
Thanks for letting us know. It sounds like there is a syntax error in the doas.conf file. Could you post the contents of the /usr/local/etc/doas.conf file here?

**Comment by ReduxRoot** [comment]
What i have on the doas.conf file is this:
`permit tiago as root`

Thanks for the quick response!

**Comment by slicer69** [comment]
Assuming your username is tiago, then this line looks correct. There are a few things which could be happening here.

1. There is a special character like a Tab in the line which is not visible. Creating a fresh doas.conf file can fix this.

2. The doas.conf file has been created where doas is not looking for it. For instance, if you created your file as /etc/doas.conf, but doas is looking in /usr/local/etc/doas.conf for its configuration.

3. Please make sure root has read access to the doas.conf file.

**Comment by ReduxRoot** [comment]
Thanks, after deleting the /usr/local/etc/doas.conf and creating a new one in /etc/doas.conf and in /usr/local/etc/doas.conf with the permission root: read & write, gives this message `doas: /usr/local/etc/doas.conf is writable by group or other` but if i change to root: read only gives again `doas: syntax error at line 1` i'm not sure where is the problem i tried creating a new one but gives the same problem, thanks for responding, i attached a print with the problem and yes my username is tiago.
![problem](https://user-images.githubusercontent.com/87225951/126874995-a012b18d-ca7e-4ff8-96af-08c043871ce9.png)

**Comment by slicer69** [comment]
Thank you for posting this. Would you please post the output of the two following commands:

     ls -l /usr/local/bin/doas

and the command

     sudo cat /usr/local/etc/doas.conf

Thank you

**Comment by ReduxRoot** [comment]
Here is the output:

![img002](https://user-images.githubusercontent.com/87225951/126877334-44ecf5a2-283b-4612-b06c-3f19bfc8f468.png)

**Comment by slicer69** [comment]
It looks like there is no newline character at the end of the first line of the doas.conf. Just open the file again and press Enter at the end of the line. There is a reference to this requirement in the doas.conf manual page:

     Entries in the doas.conf file must end with a newline character to indicate where a
     rule ends. Most text editors will add a newline or end of line character for you,
     however not all tools do. Please make sure each rule in your doas.conf file ends
     with a newline (Enter) character. Otherwise syntax checks will fail with an error
     "syntax error at line..."

**Comment by ReduxRoot** [comment]
Thanks the command is now working like a charm, probably mousepad doesn't add a newline thank you so much!

![img003](https://user-images.githubusercontent.com/87225951/126877878-81fe0efd-782c-4afc-9c26-b33a316f35ea.png)
