### ISSUE TITLE
become POSIX compliant

### ISSUE THREAD

**Issue by nyxnor** [slicer69/doas#91]
#### Vidoas and other shellscripts have the shebang is /bin/sh but they are not POSIX
* `sed -E` is not posix
* `local var` is not posix
* cmd `install` is not posix
* cmd `mktemp` is not posix

#### If agreeable, I can pr the following changes
* set -E
https://github.com/slicer69/doas/blob/c06ff5e225bf950541fa4594f6bd749e8bac9384/vidoas#L44
will become
`get_intr="$(stty -a | sed -n '/.*intr = / {s///;s/;.*$//;p;}')"`

* local
https://github.com/slicer69/doas/blob/c06ff5e225bf950541fa4594f6bd749e8bac9384/vidoas#L58
local will be removed

* install
https://github.com/slicer69/doas/blob/c06ff5e225bf950541fa4594f6bd749e8bac9384/vidoas#L234
install will become `cp -p` to preserver permissions
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cp.html#tag_20_24

* mktemp
https://github.com/slicer69/doas/blob/c06ff5e225bf950541fa4594f6bd749e8bac9384/vidoas#L160
mktemp will change for the C funtion of similar name 
tmp_doas="$(printf %s"mkstemp(${DOAS_CONF}.XXXXXX)" | m4)"
learned from here https://unix.stackexchange.com/a/614823
6 times X is posix
https://pubs.opengroup.org/onlinepubs/9699919799/functions/mkdtemp.html

**Comment by slicer69** [comment]
As far as I know the vidoas script works on all supported platforms. While the script may not be POSIX compliant, that's not really a concern as long as the script works.

The proposed changes look like they'll add complexity and, in the case of the "cp -p" command actually break the install script on some platforms.

**Comment by Jan200101** [comment]
then perhaps the shebang should not be `/bin/sh` but a shell that is compatible with the lingo `/bin/bash`

**Comment by slicer69** [comment]
No, that would break doas on all platforms that either A) don't ship with bash or B) don't place bash in /bin. The /bin/sh appears to work on all supported platforms so there is no reason to change it.
