### ISSUE TITLE
It doesn't seems to work in Solus

### ISSUE THREAD

**Issue by Marshallishere** [slicer69/doas#94]
I was trying to install the doas for Linux, but in Solus I don't have the sudo in pam.d and when I created the doas file and rebooted it  told me that had a pam authentication error.

OS: Solus 4.3

**Comment by slicer69** [comment]
I'm not really familiar with the Solus configuration of PAM. Chances are you can get around this issue by creating a file called /etc/pam.d/doas and placing an include statement for your distribution's common authentication module(s). On Debian it would be

#%PAM-1.0

     @include common-auth
     @include common-account
     @include common-session-noninteractive

I'm not sure what the include modules would be on Solus, but hopefully one of the devs or forum users can answer that part.
