### ISSUE TITLE
´doas -u user´ results in "doas: Operation not permitted"

### ISSUE THREAD

**Issue by KrischnaGabriel** [slicer69/doas#96]
`$ doas -u ...` always results in an Error:

> doas: Operation not permitted

meanwhile the bloated sudo does it.
Why and how can I resolve it?

**Distro:** Linux Mint 20.3 Una
**base debian_version (cat /etc/debian_version):** bullseye/sid
**doas version:** around one month old. Don't know what exactly, because `doas -V` does not work and the package is not in the repo.

**Comment by slicer69** [comment]
A few questions for you so we can resolve this:

1. What is the exact line you're using when you try to use the "-u" flag?

2. What does your doas.conf file look like?

3. Did you compile doas from source from this repo or install it from somewhere else?

**Comment by KrischnaGabriel** [comment]
1:
"abds" is a user I created.
`$ doas -u abds ls`
`doas: Operation not permitted`
With sudo it works:
`$ sudo -u abds ls`
`[sudo] password for user:`
The executed command doesn't seem to matter. Even when executing `echo` it happens.
2:
`$ cat /usr/local/etc/doas.conf`
`permit user as root`
"user" is the main user I use. (i know, very creative name)

3: I git cloned it and compiled it from source
Btw he promoted doas and also showed how to compile from source if someone is new to linux. 
https://youtu.be/eamEZCj-CuQ?t=355
This was how i heard about doas.

**Comment by slicer69** [comment]
If the only line in your doas.conf file is "permit user as root" then you'll need another entry allowing your default user to run commands as "abds". Something like:

     permit user as abds

Right now, if that line doesn't exist, then doas knows your user is only allowed to run commands as root, not as abds and correctly rejects the request.

**Comment by KrischnaGabriel** [comment]
Why can't i do something like `permit doas as *` or `permit doas as <ALL>`?
Obviously it's a safety feature i didn't understood, but not even root can run commands as other users without adding every user manually

**Comment by slicer69** [comment]
You can do that, it's covered in the doas.conf manual page. There's an example of doing this in the man page.
