### ISSUE TITLE
doas: syntax error at line 1

### ISSUE THREAD

**Issue by max-ishere** [slicer69/doas#97]
This is my server config file:
```
permit persist :wheel as root
```
When I try to run any command (e.g. `doas -s`) I get `doas: syntax error at line 1`
I tried pasting in a config from my laptop, also tried replacing `:wheel` with my username and it still gives me an error. 
I thought this was due to an outdated version of doas but after the update the error persists.

**Comment by slicer69** [comment]
Two things here: 

1. The "persist" keyword doesn't work with this port of doas. So either you're using different software (like OpenDoas) or you should check out the doas.conf manual page ("man doas.conf") to see which options are available.

2. Chances are there is no newline character at the end of your config. As the doas.conf manual page says...

     "Entries in the doas.conf file must end with a newline character to indicate where a rule
     ends. Most text editors will add a newline or end of line character for you, however not
     all tools do. Please make sure each rule in your doas.conf file ends with a newline (En‐
     ter) character. Otherwise syntax checks will fail with an error "syntax error at
     line..."
